package com.lexus.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * AbstractUser generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractUser  implements java.io.Serializable {


    // Fields    

     private Integer pkUserId;
     private String username;
     private String password;
     private String email;
     private String nickName;
     private String question;
     private String answer;
     private String lastLoginIp;
     private Date checkinTime;
     private Date updateTime;
     private Short version;
     private String status;
     //关联类属性
     private UserDetail userDetails;
     //关联类属性
     private Set logs = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractUser() {
    }

	/** minimal constructor */
    public AbstractUser(String username, String password) {
        this.username = username;
        this.password = password;
    }
    
    /** full constructor */
    public AbstractUser(String username, String password, String email, String nickName, String question, String answer, String lastLoginIp, Date checkinTime, Date updateTime, Short version, String status, UserDetail userDetails, Set logs) {
        this.username = username;
        this.password = password;
        this.email = email;
        this.nickName = nickName;
        this.question = question;
        this.answer = answer;
        this.lastLoginIp = lastLoginIp;
        this.checkinTime = checkinTime;
        this.updateTime = updateTime;
        this.version = version;
        this.status = status;
        this.userDetails = userDetails;
        this.logs = logs;
    }

   
    // Property accessors

    public Integer getPkUserId() {
        return this.pkUserId;
    }
    
    public void setPkUserId(Integer pkUserId) {
        this.pkUserId = pkUserId;
    }

    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getNickName() {
        return this.nickName;
    }
    
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }

    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public String getLastLoginIp() {
        return this.lastLoginIp;
    }
    
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    public Date getCheckinTime() {
        return this.checkinTime;
    }
    
    public void setCheckinTime(Date checkinTime) {
        this.checkinTime = checkinTime;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Short getVersion() {
        return this.version;
    }
    
    public void setVersion(Short version) {
        this.version = version;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public Set getLogs() {
        return this.logs;
    }
    
    public void setLogs(Set logs) {
        this.logs = logs;
    }

	/**
	 * @return userDetails
	 */
	public UserDetail getUserDetails() {
		return userDetails;
	}

	/**
	 * @param userDetails 要设置的 userDetails
	 */
	public void setUserDetails(UserDetail userDetails) {
		this.userDetails = userDetails;
	}
   








}