package com.lexus.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * AbstractTableName generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTableName  implements java.io.Serializable {


    // Fields    

     private Integer pkTableNameId;
     private String tableName;
     private String description;
     private Date checkinTime;
     private Date updateTime;
     private Short version;
     private String status;
     private Set tableFieldDictMappings = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractTableName() {
    }

	/** minimal constructor */
    public AbstractTableName(String tableName) {
        this.tableName = tableName;
    }
    
    /** full constructor */
    public AbstractTableName(String tableName, String description, Date checkinTime, Date updateTime, Short version, String status, Set tableFieldDictMappings) {
        this.tableName = tableName;
        this.description = description;
        this.checkinTime = checkinTime;
        this.updateTime = updateTime;
        this.version = version;
        this.status = status;
        this.tableFieldDictMappings = tableFieldDictMappings;
    }

   
    // Property accessors

    public Integer getPkTableNameId() {
        return this.pkTableNameId;
    }
    
    public void setPkTableNameId(Integer pkTableNameId) {
        this.pkTableNameId = pkTableNameId;
    }

    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Date getCheckinTime() {
        return this.checkinTime;
    }
    
    public void setCheckinTime(Date checkinTime) {
        this.checkinTime = checkinTime;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Short getVersion() {
        return this.version;
    }
    
    public void setVersion(Short version) {
        this.version = version;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public Set getTableFieldDictMappings() {
        return this.tableFieldDictMappings;
    }
    
    public void setTableFieldDictMappings(Set tableFieldDictMappings) {
        this.tableFieldDictMappings = tableFieldDictMappings;
    }
   








}