package com.lexus.bean;



/**
 * AbstractTableFieldDictMapping generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTableFieldDictMapping  implements java.io.Serializable {


    // Fields    

     private TableFieldDictMappingId id;
     private Dictionary dictionary;
     private TableName tableName;
     private FieldName fieldName;
     private String tableName_1;
     private String fieldName_1;


    // Constructors

    /** default constructor */
    public AbstractTableFieldDictMapping() {
    }

	/** minimal constructor */
    public AbstractTableFieldDictMapping(TableName tableName, FieldName fieldName, String tableName_1, String fieldName_1) {
        this.tableName = tableName;
        this.fieldName = fieldName;
        this.tableName_1 = tableName_1;
        this.fieldName_1 = fieldName_1;
    }
    
    /** full constructor */
    public AbstractTableFieldDictMapping(Dictionary dictionary, TableName tableName, FieldName fieldName, String tableName_1, String fieldName_1) {
        this.dictionary = dictionary;
        this.tableName = tableName;
        this.fieldName = fieldName;
        this.tableName_1 = tableName_1;
        this.fieldName_1 = fieldName_1;
    }

   
    // Property accessors

    public TableFieldDictMappingId getId() {
        return this.id;
    }
    
    public void setId(TableFieldDictMappingId id) {
        this.id = id;
    }

    public Dictionary getDictionary() {
        return this.dictionary;
    }
    
    public void setDictionary(Dictionary dictionary) {
        this.dictionary = dictionary;
    }

    public TableName getTableName() {
        return this.tableName;
    }
    
    public void setTableName(TableName tableName) {
        this.tableName = tableName;
    }

    public FieldName getFieldName() {
        return this.fieldName;
    }
    
    public void setFieldName(FieldName fieldName) {
        this.fieldName = fieldName;
    }

    public String getTableName_1() {
        return this.tableName_1;
    }
    
    public void setTableName_1(String tableName_1) {
        this.tableName_1 = tableName_1;
    }

    public String getFieldName_1() {
        return this.fieldName_1;
    }
    
    public void setFieldName_1(String fieldName_1) {
        this.fieldName_1 = fieldName_1;
    }
   








}