package com.lexus.bean;



/**
 * AbstractProductDetail generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractProductDetail  implements java.io.Serializable {


    // Fields    

     private Integer pkFkProductId;
     private Product product;
     private Long productPrice;
     private String productHabitat;


    // Constructors

    /** default constructor */
    public AbstractProductDetail() {
    }

	/** minimal constructor */
    public AbstractProductDetail(Product product) {
        this.product = product;
    }
    
    /** full constructor */
    public AbstractProductDetail(Product product, Long productPrice, String productHabitat) {
        this.product = product;
        this.productPrice = productPrice;
        this.productHabitat = productHabitat;
    }

   
    // Property accessors

    public Integer getPkFkProductId() {
        return this.pkFkProductId;
    }
    
    public void setPkFkProductId(Integer pkFkProductId) {
        this.pkFkProductId = pkFkProductId;
    }

    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    public Long getProductPrice() {
        return this.productPrice;
    }
    
    public void setProductPrice(Long productPrice) {
        this.productPrice = productPrice;
    }

    public String getProductHabitat() {
        return this.productHabitat;
    }
    
    public void setProductHabitat(String productHabitat) {
        this.productHabitat = productHabitat;
    }
   








}