package com.lexus.bean;

import java.util.Date;


/**
 * AbstractUserDetail generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractUserDetail  implements java.io.Serializable {


    // Fields    

     private Integer pkFkUserId;
     //关联类属性
     private User user;
     private String realName;
     private String gender;
     private String qq;
     private String homepage;
     private Date birthday;
     private String mobilePhone;
     private String phone;
     private String address;
     private String zipCode;
     private String interest;
     private String occupation;
     private String howKnow;
     private String isSubscribe;
     private String remark;


    // Constructors

    /** default constructor */
    public AbstractUserDetail() {
    }

	/** minimal constructor */
    public AbstractUserDetail(User user) {
        this.user = user;
    }
    
    /** full constructor */
    public AbstractUserDetail(User user, String realName, String gender, String qq, String homepage, Date birthday, String mobilePhone, String phone, String address, String zipCode, String interest, String occupation, String howKnow, String isSubscribe, String remark) {
        this.user = user;
        this.realName = realName;
        this.gender = gender;
        this.qq = qq;
        this.homepage = homepage;
        this.birthday = birthday;
        this.mobilePhone = mobilePhone;
        this.phone = phone;
        this.address = address;
        this.zipCode = zipCode;
        this.interest = interest;
        this.occupation = occupation;
        this.howKnow = howKnow;
        this.isSubscribe = isSubscribe;
        this.remark = remark;
    }

   
    // Property accessors

    public Integer getPkFkUserId() {
        return this.pkFkUserId;
    }
    
    public void setPkFkUserId(Integer pkFkUserId) {
        this.pkFkUserId = pkFkUserId;
    }

    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    public String getRealName() {
        return this.realName;
    }
    
    public void setRealName(String realName) {
        this.realName = realName;
    }

    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getQq() {
        return this.qq;
    }
    
    public void setQq(String qq) {
        this.qq = qq;
    }

    public String getHomepage() {
        return this.homepage;
    }
    
    public void setHomepage(String homepage) {
        this.homepage = homepage;
    }

    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getMobilePhone() {
        return this.mobilePhone;
    }
    
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    public String getInterest() {
        return this.interest;
    }
    
    public void setInterest(String interest) {
        this.interest = interest;
    }

    public String getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    public String getHowKnow() {
        return this.howKnow;
    }
    
    public void setHowKnow(String howKnow) {
        this.howKnow = howKnow;
    }

    public String getIsSubscribe() {
        return this.isSubscribe;
    }
    
    public void setIsSubscribe(String isSubscribe) {
        this.isSubscribe = isSubscribe;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
   








}