package com.lexus.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * AbstractFieldName generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractFieldName  implements java.io.Serializable {


    // Fields    

     private Integer pkFieldNameId;
     private String fieldName;
     private String fieldType;
     private String fieldDefault;
     private String fieldDescription;
     private Date checkinTime;
     private Date updateTime;
     private Short version;
     private String status;
     private Set tableFieldDictMappings = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractFieldName() {
    }

	/** minimal constructor */
    public AbstractFieldName(String fieldName) {
        this.fieldName = fieldName;
    }
    
    /** full constructor */
    public AbstractFieldName(String fieldName, String fieldType, String fieldDefault, String fieldDescription, Date checkinTime, Date updateTime, Short version, String status, Set tableFieldDictMappings) {
        this.fieldName = fieldName;
        this.fieldType = fieldType;
        this.fieldDefault = fieldDefault;
        this.fieldDescription = fieldDescription;
        this.checkinTime = checkinTime;
        this.updateTime = updateTime;
        this.version = version;
        this.status = status;
        this.tableFieldDictMappings = tableFieldDictMappings;
    }

   
    // Property accessors

    public Integer getPkFieldNameId() {
        return this.pkFieldNameId;
    }
    
    public void setPkFieldNameId(Integer pkFieldNameId) {
        this.pkFieldNameId = pkFieldNameId;
    }

    public String getFieldName() {
        return this.fieldName;
    }
    
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    public String getFieldType() {
        return this.fieldType;
    }
    
    public void setFieldType(String fieldType) {
        this.fieldType = fieldType;
    }

    public String getFieldDefault() {
        return this.fieldDefault;
    }
    
    public void setFieldDefault(String fieldDefault) {
        this.fieldDefault = fieldDefault;
    }

    public String getFieldDescription() {
        return this.fieldDescription;
    }
    
    public void setFieldDescription(String fieldDescription) {
        this.fieldDescription = fieldDescription;
    }

    public Date getCheckinTime() {
        return this.checkinTime;
    }
    
    public void setCheckinTime(Date checkinTime) {
        this.checkinTime = checkinTime;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Short getVersion() {
        return this.version;
    }
    
    public void setVersion(Short version) {
        this.version = version;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public Set getTableFieldDictMappings() {
        return this.tableFieldDictMappings;
    }
    
    public void setTableFieldDictMappings(Set tableFieldDictMappings) {
        this.tableFieldDictMappings = tableFieldDictMappings;
    }
   








}