package com.lexus.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * AbstractDictionary generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractDictionary  implements java.io.Serializable {


    // Fields    

     private Integer pkDictionaryId;
     private String dictionaryName;
     private Short isMultinest;
     private Date checkinTime;
     private Date updateTime;
     private Short version;
     private String status;
     private Set tableFieldDictMappings = new HashSet(0);
     private Set dictionaryLibs = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractDictionary() {
    }

	/** minimal constructor */
    public AbstractDictionary(String dictionaryName) {
        this.dictionaryName = dictionaryName;
    }
    
    /** full constructor */
    public AbstractDictionary(String dictionaryName, Short isMultinest, Date checkinTime, Date updateTime, Short version, String status, Set tableFieldDictMappings, Set dictionaryLibs) {
        this.dictionaryName = dictionaryName;
        this.isMultinest = isMultinest;
        this.checkinTime = checkinTime;
        this.updateTime = updateTime;
        this.version = version;
        this.status = status;
        this.tableFieldDictMappings = tableFieldDictMappings;
        this.dictionaryLibs = dictionaryLibs;
    }
   
    // Property accessors

    public Integer getPkDictionaryId() {
        return this.pkDictionaryId;
    }
    
    public void setPkDictionaryId(Integer pkDictionaryId) {
        this.pkDictionaryId = pkDictionaryId;
    }

    public String getDictionaryName() {
        return this.dictionaryName;
    }
    
    public void setDictionaryName(String dictionaryName) {
        this.dictionaryName = dictionaryName;
    }

    public Short getIsMultinest() {
        return this.isMultinest;
    }
    
    public void setIsMultinest(Short isMultinest) {
        this.isMultinest = isMultinest;
    }

    public Date getCheckinTime() {
        return this.checkinTime;
    }
    
    public void setCheckinTime(Date checkinTime) {
        this.checkinTime = checkinTime;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Short getVersion() {
        return this.version;
    }
    
    public void setVersion(Short version) {
        this.version = version;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public Set getTableFieldDictMappings() {
        return this.tableFieldDictMappings;
    }
    
    public void setTableFieldDictMappings(Set tableFieldDictMappings) {
        this.tableFieldDictMappings = tableFieldDictMappings;
    }

	/**
	 * @return dictionaryLibs
	 */
	public Set getDictionaryLibs() {
		return dictionaryLibs;
	}

	/**
	 * @param dictionaryLibs 要设置的 dictionaryLibs
	 */
	public void setDictionaryLibs(Set dictionaryLibs) {
		this.dictionaryLibs = dictionaryLibs;
	}

   








}