package com.lexus.bean;

import java.util.Date;
import java.util.List;


/**
 * AbstractProduct generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractProduct  implements java.io.Serializable {


    // Fields    

     private Integer pkProductId;
     private String productName;
     private String productDescription;
     private List productCategories;
     private List productAttachments;
     private Date checkinTime;
     private Date updateTime;
     private Short version;
     private String status;
     private ProductDetail productDetail;

    // Constructors

     /**
 	 * @param pkProductId
 	 * @param productName
 	 * @param productDescription
 	 * @param productCategories
 	 * @param productAttachments
 	 * @param checkinTime
 	 * @param updateTime
 	 * @param version
 	 * @param status
 	 * @param productDetail
 	 */
 	public AbstractProduct(Integer pkProductId, String productName, String productDescription, List productCategories, List productAttachments, Date checkinTime, Date updateTime, Short version, String status, ProductDetail productDetail) {
 		super();
 		this.pkProductId = pkProductId;
 		this.productName = productName;
 		this.productDescription = productDescription;
 		this.productCategories = productCategories;
 		this.productAttachments = productAttachments;
 		this.checkinTime = checkinTime;
 		this.updateTime = updateTime;
 		this.version = version;
 		this.status = status;
 		this.productDetail = productDetail;
 	}


	/** default constructor */
    public AbstractProduct() {
    }

    
    /** full constructor */
    public AbstractProduct(String productName, String productDescription, List productCategories, List productAttachments, Date checkinTime, Date updateTime, Short version, String status, ProductDetail productDetail) {
        this.productName = productName;
        this.productDescription = productDescription;
        this.productCategories = productCategories;
        this.productAttachments = productAttachments;
        this.checkinTime = checkinTime;
        this.updateTime = updateTime;
        this.version = version;
        this.status = status;
        this.productDetail = productDetail;
    }

   
    // Property accessors

    public Integer getPkProductId() {
        return this.pkProductId;
    }
    
    public void setPkProductId(Integer pkProductId) {
        this.pkProductId = pkProductId;
    }

    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getProductDescription() {
        return this.productDescription;
    }
    
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }

    public List getProductCategories() {
        return this.productCategories;
    }
    
    public void setProductCategories(List productCategories) {
        this.productCategories = productCategories;
    }

    public List getProductAttachments() {
        return this.productAttachments;
    }
    
    public void setProductAttachments(List productAttachments) {
        this.productAttachments = productAttachments;
    }

    public Date getCheckinTime() {
        return this.checkinTime;
    }
    
    public void setCheckinTime(Date checkinTime) {
        this.checkinTime = checkinTime;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Short getVersion() {
        return this.version;
    }
    
    public void setVersion(Short version) {
        this.version = version;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }


	/**
	 * @return productDetail
	 */
	public ProductDetail getProductDetail() {
		return productDetail;
	}


	/**
	 * @param productDetail 要设置的 productDetail
	 */
	public void setProductDetail(ProductDetail productDetail) {
		this.productDetail = productDetail;
	}


   








}