package com.lexus.bean;

import java.util.Date;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;


/**
 * AbstractAttachment generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractAttachment  implements java.io.Serializable {

	private int hashValue = 0;
    // Fields    

     private Integer pkAttachmentId;
     private DictionaryLib dictionaryLibByAttachmentType;
     private DictionaryLib dictionaryLibByExtendName;
     private String attachmentTitle;
     private String attachmentUrl;
     private String attachmentDescription;
     private String linkUrl;
     private Date checkinTime;
     private Date updateTime;
     private Short version;
     private String status;


    // Constructors

    /** default constructor */
    public AbstractAttachment() {
    }

	/** minimal constructor */
    public AbstractAttachment(DictionaryLib dictionaryLibByAttachmentType, DictionaryLib dictionaryLibByExtendName) {
        this.dictionaryLibByAttachmentType = dictionaryLibByAttachmentType;
        this.dictionaryLibByExtendName = dictionaryLibByExtendName;
    }
    
    /** full constructor */
    public AbstractAttachment(DictionaryLib dictionaryLibByAttachmentType, DictionaryLib dictionaryLibByExtendName, String attachmentTitle, String attachmentUrl, String attachmentDescription, String linkUrl, Date checkinTime, Date updateTime, Short version, String status) {
        this.dictionaryLibByAttachmentType = dictionaryLibByAttachmentType;
        this.dictionaryLibByExtendName = dictionaryLibByExtendName;
        this.attachmentTitle = attachmentTitle;
        this.attachmentUrl = attachmentUrl;
        this.attachmentDescription = attachmentDescription;
        this.linkUrl = linkUrl;
        this.checkinTime = checkinTime;
        this.updateTime = updateTime;
        this.version = version;
        this.status = status;
    }

   
    // Property accessors

    public Integer getPkAttachmentId() {
        return this.pkAttachmentId;
    }
    
    public void setPkAttachmentId(Integer pkAttachmentId) {
        this.pkAttachmentId = pkAttachmentId;
    }

    public DictionaryLib getDictionaryLibByAttachmentType() {
        return this.dictionaryLibByAttachmentType;
    }
    
    public void setDictionaryLibByAttachmentType(DictionaryLib dictionaryLibByAttachmentType) {
        this.dictionaryLibByAttachmentType = dictionaryLibByAttachmentType;
    }

    public DictionaryLib getDictionaryLibByExtendName() {
        return this.dictionaryLibByExtendName;
    }
    
    public void setDictionaryLibByExtendName(DictionaryLib dictionaryLibByExtendName) {
        this.dictionaryLibByExtendName = dictionaryLibByExtendName;
    }

    public String getAttachmentTitle() {
        return this.attachmentTitle;
    }
    
    public void setAttachmentTitle(String attachmentTitle) {
        this.attachmentTitle = attachmentTitle;
    }

    public String getAttachmentUrl() {
        return this.attachmentUrl;
    }
    
    public void setAttachmentUrl(String attachmentUrl) {
        this.attachmentUrl = attachmentUrl;
    }

    public String getAttachmentDescription() {
        return this.attachmentDescription;
    }
    
    public void setAttachmentDescription(String attachmentDescription) {
        this.attachmentDescription = attachmentDescription;
    }

    public String getLinkUrl() {
        return this.linkUrl;
    }
    
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl;
    }

    public Date getCheckinTime() {
        return this.checkinTime;
    }
    
    public void setCheckinTime(Date checkinTime) {
        this.checkinTime = checkinTime;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Short getVersion() {
        return this.version;
    }
    
    public void setVersion(Short version) {
        this.version = version;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

	/**
	 * @see java.lang.Object#equals(Object)
	 */
	public boolean equals(Object object) {
		if(object==null)
			return false;
		if (!(object instanceof AbstractAttachment)) {
			return false;
		}
		Attachment that=(Attachment)object;
		if(this.getPkAttachmentId()==null||that.getPkAttachmentId()==null)
			return false;
		return this.getPkAttachmentId().equals(that.getPkAttachmentId());
	}

	/**
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		if(this.hashValue==0)
		{
			int result=17;
			int idValue=this.getPkAttachmentId()==null?0:this.getPkAttachmentId().hashCode();
			result=result*37+idValue;
			this.hashValue=result;
		}
		return this.hashValue;
	}
   








}