package com.lexus.bean;

import java.util.Date;


/**
 * AbstractLog generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractLog  implements java.io.Serializable {


    // Fields    

     private Integer pkLogId;
     //关联类属性
     private User user;
     private String operateDescription;
     private String operaterIp;
     private Date checkinTime;
     private String status;


    // Constructors

    /** default constructor */
    public AbstractLog() {
    }

	/** minimal constructor */
    public AbstractLog(User user) {
        this.user = user;
    }
    
    /** full constructor */
    public AbstractLog(User user, String operateDescription, String operaterIp, Date checkinTime, String status) {
        this.user = user;
        this.operateDescription = operateDescription;
        this.operaterIp = operaterIp;
        this.checkinTime = checkinTime;
        this.status = status;
    }

   
    // Property accessors

    public Integer getPkLogId() {
        return this.pkLogId;
    }
    
    public void setPkLogId(Integer pkLogId) {
        this.pkLogId = pkLogId;
    }

    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    public String getOperateDescription() {
        return this.operateDescription;
    }
    
    public void setOperateDescription(String operateDescription) {
        this.operateDescription = operateDescription;
    }

    public String getOperaterIp() {
        return this.operaterIp;
    }
    
    public void setOperaterIp(String operaterIp) {
        this.operaterIp = operaterIp;
    }

    public Date getCheckinTime() {
        return this.checkinTime;
    }
    
    public void setCheckinTime(Date checkinTime) {
        this.checkinTime = checkinTime;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
   








}