package com.lexus.bean;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * Attachment generated by MyEclipse - Hibernate Tools
 */
public class Attachment extends AbstractAttachment implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** default constructor */
    public Attachment() {
    }

	/** minimal constructor */
    public Attachment(DictionaryLib dictionaryLibByAttachmentType, DictionaryLib dictionaryLibByExtendName) {
        super(dictionaryLibByAttachmentType, dictionaryLibByExtendName);        
    }
    
    /** full constructor */
    public Attachment(DictionaryLib dictionaryLibByAttachmentType, DictionaryLib dictionaryLibByExtendName, String attachmentTitle, String attachmentUrl, String attachmentDescription, String linkUrl, Date checkinTime, Date updateTime, Short version, String status) {
        super(dictionaryLibByAttachmentType, dictionaryLibByExtendName, attachmentTitle, attachmentUrl, attachmentDescription, linkUrl, checkinTime, updateTime, version, status);        
    }
   
}
