package com.lexus.bean;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;
import java.util.Set;


/**
 * Dictionary generated by MyEclipse - Hibernate Tools
 */
public class Dictionary extends AbstractDictionary implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** default constructor */
    public Dictionary() {
    }

	/** minimal constructor */
    public Dictionary(String dictionaryName) {
        super(dictionaryName);        
    }
    
    /** full constructor */
    public Dictionary(String dictionaryName, Short isMultinest, Date checkinTime, Date updateTime, Short version, String status, Set tableFieldDictMappings, Set dictionaryLibs) {
        super(dictionaryName, isMultinest, checkinTime, updateTime, version, status, tableFieldDictMappings, dictionaryLibs);        
    }
   
}
