package com.lexus.bean;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;
import java.util.Set;


/**
 * FieldName generated by MyEclipse - Hibernate Tools
 */
public class FieldName extends AbstractFieldName implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** default constructor */
    public FieldName() {
    }

	/** minimal constructor */
    public FieldName(String fieldName) {
        super(fieldName);        
    }
    
    /** full constructor */
    public FieldName(String fieldName, String fieldType, String fieldDefault, String fieldDescription, Date checkinTime, Date updateTime, Short version, String status, Set tableFieldDictMappings) {
        super(fieldName, fieldType, fieldDefault, fieldDescription, checkinTime, updateTime, version, status, tableFieldDictMappings);        
    }
   
}
