package com.lexus.bean;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * Log generated by MyEclipse - Hibernate Tools
 */
public class Log extends AbstractLog implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	// Constructors

    /** default constructor */
    public Log() {
    }

	/** minimal constructor */
    public Log(User user) {
        super(user);        
    }
    
    /** full constructor */
    public Log(User user, String operateDescription, String operaterIp, Date checkinTime, String status) {
        super(user, operateDescription, operaterIp, checkinTime, status);        
    }
   
}
