package com.lexus.bean;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;
import java.util.List;


/**
 * Product generated by MyEclipse - Hibernate Tools
 */
public class Product extends AbstractProduct implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;


	/** default constructor */
    public Product() {
    }

    
    /** full constructor */
//    public Product(String productName, String productDescription, String productCategories, String productAttachments, Date checkinTime, Date updateTime, Short version, String status, ProductDetail productDetail) {
//        super(productName, productDescription, productCategories, productAttachments, checkinTime, updateTime, version, status, productDetail);        
//    }
    public Product(String productName, String productDescription, List productCategories, List productAttachments, Date checkinTime, Date updateTime, Short version, String status, ProductDetail productDetail) {
        super(productName, productDescription, productCategories, productAttachments, checkinTime, updateTime, version, status, productDetail);        
    }
    public Product(Integer pkProductId, String productName, String productDescription, List productCategories, List productAttachments, Date checkinTime, Date updateTime, Short version, String status, ProductDetail productDetail) {
    	super(pkProductId,productName,productDescription,productCategories,productAttachments,checkinTime,updateTime,version,status,productDetail);
 	}
    
}
