package com.lexus.bean;
// Generated by MyEclipse - Hibernate Tools



/**
 * TableFieldDictMappingId generated by MyEclipse - Hibernate Tools
 */
public class TableFieldDictMappingId extends AbstractTableFieldDictMappingId implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;


	/** default constructor */
    public TableFieldDictMappingId() {
    }

    
    /** full constructor */
    public TableFieldDictMappingId(Integer pkFkTableNameId, Integer pkFkFieldNameId) {
        super(pkFkTableNameId, pkFkFieldNameId);        
    }
   
}
