package com.lexus.bean;
// Generated by MyEclipse - Hibernate Tools



/**
 * TableFieldDictMapping generated by MyEclipse - Hibernate Tools
 */
public class TableFieldDictMapping extends AbstractTableFieldDictMapping implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** default constructor */
    public TableFieldDictMapping() {
    }

	/** minimal constructor */
    public TableFieldDictMapping(TableName tableName, FieldName fieldName, String tableName_1, String fieldName_1) {
        super(tableName, fieldName, tableName_1, fieldName_1);        
    }
    
    /** full constructor */
    public TableFieldDictMapping(Dictionary dictionary, TableName tableName, FieldName fieldName, String tableName_1, String fieldName_1) {
        super(dictionary, tableName, fieldName, tableName_1, fieldName_1);        
    }
   
}
