package com.lexus.bean;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;
import java.util.Set;


/**
 * TableName generated by MyEclipse - Hibernate Tools
 */
public class TableName extends AbstractTableName implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** default constructor */
    public TableName() {
    }

	/** minimal constructor */
    public TableName(String tableName) {
        super(tableName);        
    }
    
    /** full constructor */
    public TableName(String tableName, String description, Date checkinTime, Date updateTime, Short version, String status, Set tableFieldDictMappings) {
        super(tableName, description, checkinTime, updateTime, version, status, tableFieldDictMappings);        
    }
   
}
