package com.lexus.bean;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;
import java.util.Set;


/**
 * User generated by MyEclipse - Hibernate Tools
 */
public class User extends AbstractUser implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** default constructor */
    public User() {
    }

	/** minimal constructor */
    public User(String username, String password) {
        super(username, password);        
    }
    
    /** full constructor */
    public User(String username, String password, String email, String nickName, String question, String answer, String lastLoginIp, Date checkinTime, Date updateTime, Short version, String status, UserDetail userDetails, Set logs) {
        super(username, password, email, nickName, question, answer, lastLoginIp, checkinTime, updateTime, version, status, userDetails, logs);        
    }
   
}
