package com.lexus.bean;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * UserDetail generated by MyEclipse - Hibernate Tools
 */
public class UserDetail extends AbstractUserDetail implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** default constructor */
    public UserDetail() {
    }

	/** minimal constructor */
    public UserDetail(User user) {
        super(user);        
    }
    
    /** full constructor */
    public UserDetail(User user, String realName, String gender, String qq, String homepage, Date birthday, String mobilePhone, String phone, String address, String zipCode, String interest, String occupation, String howKnow, String isSubscribe, String remark) {
        super(user, realName, gender, qq, homepage, birthday, mobilePhone, phone, address, zipCode, interest, occupation, howKnow, isSubscribe, remark);        
    }
   
}
