/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.lexus.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.lexus.util.CharacterOperate;

/** 
 * MyEclipse Struts
 * Creation date: 06-06-2007
 * 
 * XDoclet definition:
 * @struts.form name="productEditForm"
 */
public class ProductEditForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** price property */
	private String price;

	/** productName property */
	private String productName;

	/** categoryName property */
	private String categoryName;

	/** status property */
	private String status;

	/** habitat property */
	private String habitat;

	/** categoryId property */
	private String categoryId;

	/** productDescription property */
	private String productDescription;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors infos=new ActionErrors();
		if((this.categoryName==null)||(this.categoryName.length()<1))
		{
			infos.add("categorName",new ActionError("error.struts.form.productadd.categoryname.required"));
		}
		if(this.categoryId==null||this.categoryId.length()<1)
		{
			infos.add("info",new ActionError("error.struts.form.productadd.invalid"));
		}
		if(this.productName==null||this.productName.length()<1)
		{
			infos.add("productName",new ActionError("error.struts.form.productadd.categoryname.required"));
		}
		if(this.price==null||this.price.length()<1||this.price.equals(""))
		{
			this.price="0";
		}
		else
		{
			if(!CharacterOperate.isFloat(this.price))
			{
				infos.add("price",new ActionError("error.struts.form.productadd.price.invalid"));
			}
		}
		return infos;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the price.
	 * @return String
	 */
	public String getPrice() {
		return price;
	}

	/** 
	 * Set the price.
	 * @param price The price to set
	 */
	public void setPrice(String price) {
		this.price = price;
	}

	/** 
	 * Returns the productName.
	 * @return String
	 */
	public String getProductName() {
		return productName;
	}

	/** 
	 * Set the productName.
	 * @param productName The productName to set
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

	/** 
	 * Returns the categoryName.
	 * @return String
	 */
	public String getCategoryName() {
		return categoryName;
	}

	/** 
	 * Set the categoryName.
	 * @param categoryName The categoryName to set
	 */
	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	/** 
	 * Returns the status.
	 * @return String
	 */
	public String getStatus() {
		return status;
	}

	/** 
	 * Set the status.
	 * @param status The status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/** 
	 * Returns the habitat.
	 * @return String
	 */
	public String getHabitat() {
		return habitat;
	}

	/** 
	 * Set the habitat.
	 * @param habitat The habitat to set
	 */
	public void setHabitat(String habitat) {
		this.habitat = habitat;
	}

	/** 
	 * Returns the categoryId.
	 * @return String
	 */
	public String getCategoryId() {
		return categoryId;
	}

	/** 
	 * Set the categoryId.
	 * @param categoryId The categoryId to set
	 */
	public void setCategoryId(String categoryId) {
		this.categoryId = categoryId;
	}

	/** 
	 * Returns the productDescription.
	 * @return String
	 */
	public String getProductDescription() {
		return productDescription;
	}

	/** 
	 * Set the productDescription.
	 * @param productDescription The productDescription to set
	 */
	public void setProductDescription(String productDescription) {
		this.productDescription = productDescription;
	}
}