/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.lexus.struts.form;

import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-30-2007
 * 
 * XDoclet definition:
 * @struts.form name="userListForm"
 */
public class UserListForm extends ValidatorForm {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
}