/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.lexus.struts.action;

import java.io.IOException;
import java.util.Iterator;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.jdom.Document;
import org.jdom.Element;
import org.jdom.output.XMLOutputter;

import com.lexus.bean.Dictionary;

/** 
 * MyEclipse Struts
 * Creation date: 05-25-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class CategoryListAction extends BaseAction {
	/**
	 * Logger for this class
	 */
	private static final Log log = LogFactory.getLog(CategoryListAction.class);

	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws IOException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		if(log.isInfoEnabled())
		{
			log.info("执行了execute方法");
		}
        response.setContentType("text/xml; charset=UTF-8");
        response.setHeader("Cache-Control", "no-cache");
        List list=this.getDictionaryService().findByAll();
        Iterator iter=list.iterator();
        Document doc=new Document();
        Element root=new Element("tree");
        doc.setRootElement(root);
        while(iter.hasNext())
        {
        	Dictionary dictionary=(Dictionary)iter.next();
        	Element e=new Element("tree");
        	e.setAttribute("text",dictionary.getDictionaryName());
        	e.setAttribute("target","mainFrame");
        	e.setAttribute("action","dictionaryDetail.do?act=show&id="+dictionary.getPkDictionaryId().toString());
//        	e.setAttribute("action","categoryDetail.jsp?parentId=0&dictionaryId="+dictionary.getPkDictionaryId().toString());
        	e.setAttribute("src","categoryDetail.do?act=buildDictionaries&parentId=0&dictionaryId="+dictionary.getPkDictionaryId().toString());
        	doc.getRootElement().addContent(e);
        }
        XMLOutputter xout=new XMLOutputter();
        xout.output(doc, response.getWriter());
        response.getWriter().close();
		return null;
	}
}
