/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.lexus.struts.action;


import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.lexus.bean.User;
import com.lexus.struts.form.LoginForm;
import com.lexus.util.Constans;

/** 
 * MyEclipse Struts
 * Creation date: 04-27-2007
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" input="/manage/login.jsp" scope="request" validate="true"
 */
public class LoginAction extends BaseAction {
	/**
	 * Logger for this class
	 */
//	private static final Log log= LogFactory.getLog(LoginAction.class);

	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub
		
		if (log.isDebugEnabled()) {
			log.debug("execute(ActionMapping, ActionForm, HttpServletRequest, HttpServletResponse) - ======test");
		}
		String username = loginForm.getUsername();
		String password = loginForm.getPassword();
		boolean flag=this.getUserService().loginValidate(username, password);

		if (log.isInfoEnabled()) {
			log.info("flag="+String.valueOf(flag));
		}
		if(flag)
		{
			//登录成功,设置session,并进行跳转
			User user=(User)this.getUserService().findByUsername(username).get(0);
			HttpSession session=request.getSession(false);
			session.setAttribute(Constans.SESSION_USER, user);
			return mapping.findForward(Constans.PAGE_MAIN);
		}
		else
		{
			//设置出错信息
			ActionMessages errors=new ActionMessages();
			errors.add("info",new ActionMessage("error.struts.action.login.info"));
			if(!errors.isEmpty())
			{
				this.saveErrors(request, errors);
			}
			return mapping.getInputForward();
		}


	}
}