/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.lexus.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.lexus.util.Constans;

/** 
 * MyEclipse Struts
 * Creation date: 04-30-2007
 * 
 * XDoclet definition:
 * @struts.action path="/logout" name="logoutForm" input="/manage/logout.jsp" scope="request" validate="true"
 */
public class LogoutAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//注销session并跳转
		request.getSession().invalidate();
		return mapping.findForward(Constans.PAGE_LOGIN);
	}
}